import json

def parse_fast_log(log_file):
    """Parse fast.log file generated by Suricata."""
    with open(log_file, 'r') as f:
        lines = f.readlines()
        for line in lines:
            # Process each line in fast.log
            print(line.strip())  

def parse_eve_json(json_file):
    """Parse eve.json file generated by Suricata."""
    with open(json_file, 'r') as f:
        data = json.load(f)
        for event in data['events']:
            # Extract relevant information from each event
            timestamp = event['timestamp']
            alert_signature = event['alert']['signature']
            src_ip = event['src_ip']
            dest_ip = event['dest_ip']
            print(f"Timestamp: {timestamp}, Signature: {alert_signature}, Source IP: {src_ip}, Destination IP: {dest_ip}")

def main():
    fast_log_file = '/var/log/suricata/fast.log'
    eve_json_file = '/var/log/suricata/eve.json'

    print("Analyzing fast.log:")
    parse_fast_log(fast_log_file)

    print("\nAnalyzing eve.json:")
    parse_eve_json(eve_json_file)

if __name__ == "__main__":
    main()
